contact_links:
    - name: â“ Questions and Help ğŸ¤”
      url: https://discord.com/channels/937858703112155166/969272658501976117
      about: This issue tracker is not for support questions. Please refer to the community for more help. 
